# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "d1161c0f57423b76555b0b2f6a11b762"
name = "Artiz COD Form"
application_url = "https://artiz-cod-form.digitaneo.workers.dev"
embedded = true

[build]
automatically_update_urls_on_dev = true

[webhooks]
api_version = "2026-07"

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "read_customers,write_customers,write_draft_orders,read_draft_orders,read_inventory,read_orders,write_orders,read_products,write_products"
optional_scopes = [ ]
use_legacy_install_flow = false

[auth]
redirect_urls = [ "https://artiz-cod-form.digitaneo.workers.dev/callback" ]
